export const RECIPE_REQUEST = "ADD_RECIPE_REQUEST";
export const RECIPE_FAILURE = "ADD_RECIPE_FAILURE";

// GET
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";